version: 2.1
orbs:
  node: circleci/node@5.2.0
  browser-tools: circleci/browser-tools@1.4.6
jobs:
  lint:
    docker:
      - image: cimg/node:20.11.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Lint
          command: npm run lint
  e2e-test:
    docker:
      - image: cimg/node:20.11.0-browsers
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build app
          command: npm run build
      - run:
          name: Run e2e tests
          command: npm run test:e2e
  unit-test:
    docker:
      - image: cimg/node:20.11.0-browsers
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run unit tests
          command: npm run test:unit
workflows:
  lint_and_test:
    jobs:
      - lint
      - e2e-test:
          requires:
            - lint
      - unit-test:
          requires:
            - lint
