version: 2.1
orbs:
  node: circleci/node@5.1
  browser-tools: circleci/browser-tools@1.4.1
jobs:
  lint:
    docker:
      - image: cimg/node:18.14.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Lint
          command: npm run lint
  e2e-test:
    docker:
      - image: cimg/node:18.14.0-browsers
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run app in the background
          command: npm run dev
          background: true
      - run:
          name: Run e2e tests
          command: npm run e2e
  unit-test:
    docker:
      - image: cimg/node:18.14.0-browsers
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run unit tests
          command: npm test
  build:
    docker:
      - image: cimg/node:18.14.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: npm run build
workflows:
  test_and_build:
    jobs:
      - lint
      - e2e-test:
          requires:
            - lint
      - unit-test:
          requires:
            - lint
      - build:
          requires:
            - e2e-test
            - unit-test
